<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 PR.gltf --transform
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers, useFrame } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { spring } from 'svelte/motion';

	export const ref = new Group();

	const gltf = useGltf('/PR-transformed.glb', { useDraco: true });
	const scale = spring(1);
  let rotation = 0
  useFrame((state, delta) => {
    rotation += delta
  })
	const component = forwardEventHandlers();
</script>

<T
	is={ref}
	dispose={false}
	{...$$restProps}
	bind:this={$component}
	scale={$scale}
  rotation.y={rotation}
	on:pointerenter={() => scale.set(1.5)}
	on:pointerleave={() => scale.set(1)}
>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Sphere001_1.geometry} material={gltf.materials['Material.001']} />
		<T.Mesh geometry={gltf.nodes.Sphere001_2.geometry} material={gltf.materials['Material.003']} />
		<T.Mesh geometry={gltf.nodes.Sphere001_3.geometry} material={gltf.materials['Material.002']} />
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
